name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  WIN_SCRIPT_ZIP_NAME: 'embykeeper-win-v2.6.33.zip'
  WIN_GUI_EXE_NAME: 'embykeeper-win-v2.6.33.exe'

permissions:
  contents: write

jobs:
  win-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Archive Windows Installer Script Version
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: ${{ env.WIN_SCRIPT_ZIP_NAME }}
          directory: 'windows/installer-script'
          exclusions: 'python-* desktop.ini'
      - name: Save Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.WIN_SCRIPT_ZIP_NAME }}
          path: windows/installer-script/${{ env.WIN_SCRIPT_ZIP_NAME }}
  win-gui:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build PyAES
        run: |
          pip wheel pyaes==1.6.1 -w windows/installer-gui/Resources
      - name: Build Windows Installer GUI Version
        run: |
          python -m pip install -U pynsistfix
          pynsist installer.cfg
          mv build/nsis/Embykeeper.exe ${{ env.WIN_GUI_EXE_NAME }}
      - name: Save Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.WIN_GUI_EXE_NAME }}
          path: ${{ env.WIN_GUI_EXE_NAME }}
  upload:
    needs:
      - win-script
      - win-gui
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifact [Windows Installer Script Version]
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.WIN_SCRIPT_ZIP_NAME }}
      - name: Download Artifact [Windows Installer GUI Version]
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.WIN_GUI_EXE_NAME }}
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          draft: true
          artifacts: '${{ env.WIN_SCRIPT_ZIP_NAME }},${{ env.WIN_GUI_EXE_NAME }}'
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: '.github/RELEASE_BODY.md'
